create TABLE FCV (
	index INT,
	month_submitted INT,
	year_submitted INT,
	last_page INT,
	previous_PHEV INT,
	previous_BEVs INT,
	previous_HEVs INT,
	previous_CNGs INT,
	household_income INT,
	importance INT,
	home_ownership INT,
	home_type INT,
	education INT,
	longest_trip FLOAT,
	number_trips INT,
	commute FLOAT,
	household_pop INT,
	age INT,
	gender INT,
	number_vehicles INT,
	VMT_estimate INT,
	Dummy VARCHAR(50),
	model_year INT,
	manufacturer VARCHAR(50),
	model VARCHAR(50)	
);
